baseurl: http://yjc.me/
disablePathToLower: true
languageCode: en-us
title: 简而言之 / Just yang's words.

paginate: 40
paginatePath: 'page'

permalinks:
  landing: /:slug/
  blog: /:slug/

params:
  analytics: 'UA-1080811-15'  
  disqus: 'yjc'
  copyright: "Copyright &copy; 2015 Jesse Yang."
  author: 杨建超
  author_en: Jesse Yang
  lang: zh  # default language of your site
  languages:
    en: English
    zh: 中文
...
...
